// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADK4WbPr6bzOeOqdkCyU37qiqz5CIs6OM',
    appId: '1:53766172392:web:957df3dc50288f2be1235d',
    messagingSenderId: '53766172392',
    projectId: 'cure-2825c',
    authDomain: 'cure-2825c.firebaseapp.com',
    storageBucket: 'cure-2825c.appspot.com',
    measurementId: 'G-S55FJQ8W45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XERlXUIe_HeBHIvBJs5kVeW6Q1KBqdo',
    appId: '1:53766172392:android:76234634cb9bb40be1235d',
    messagingSenderId: '53766172392',
    projectId: 'cure-2825c',
    storageBucket: 'cure-2825c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkHThydy3ieVpYJnU4AYTm_o9OFLbxOGI',
    appId: '1:53766172392:ios:07230df74066d6e8e1235d',
    messagingSenderId: '53766172392',
    projectId: 'cure-2825c',
    storageBucket: 'cure-2825c.appspot.com',
    iosBundleId: 'com.example.cure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHThydy3ieVpYJnU4AYTm_o9OFLbxOGI',
    appId: '1:53766172392:ios:8c45751008c913cce1235d',
    messagingSenderId: '53766172392',
    projectId: 'cure-2825c',
    storageBucket: 'cure-2825c.appspot.com',
    iosBundleId: 'com.example.cure.RunnerTests',
  );
}
